//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managermentSmartphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineItems
    {
        public int codeorder { get; set; }
        public int codeSmartphone { get; set; }
        public Nullable<int> number { get; set; }
        public string unitprice { get; set; }
    
        public virtual odrers odrers { get; set; }
        public virtual SmartPhone SmartPhone { get; set; }
    }
}
