//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managermentSmartphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odrers
    {
        public odrers()
        {
            this.lineItems = new HashSet<lineItems>();
        }
    
        public int codeorders { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<int> deliverystatus { get; set; }
        public Nullable<System.DateTime> ordersdate { get; set; }
        public Nullable<System.DateTime> shippingdate { get; set; }
        public Nullable<int> codecustomer { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual ICollection<lineItems> lineItems { get; set; }
    }
}
