//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managermentSmartphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartPhone
    {
        public SmartPhone()
        {
            this.lineItems = new HashSet<lineItems>();
        }
    
        public int codeSmartphone { get; set; }
        public string nameSmartphone { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public string imageSmartphone { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<int> numberExistence { get; set; }
        public Nullable<int> codemanufacturer { get; set; }
        public Nullable<int> codetheme { get; set; }
        public Nullable<int> news { get; set; }
    
        public virtual ICollection<lineItems> lineItems { get; set; }
        public virtual manufacturer manufacturer { get; set; }
        public virtual theme theme { get; set; }
    }
}
