//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managermentSmartphone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class theme
    {
        public theme()
        {
            this.SmartPhone = new HashSet<SmartPhone>();
        }
    
        public int codetheme { get; set; }
        public string nametheme { get; set; }
    
        public virtual ICollection<SmartPhone> SmartPhone { get; set; }
    }
}
